[minio]
url="localhost:9000"
access_key="minio_user"
secret_key="minio_password"
bucket="rag-pdf-source"

[sqlite]
dir="./sqlite_db"

[qdrant]
url="http://localhost:6333"

[server]
port=50051

[rag]
collection="pdf-fixed"
model="qwen3-embedding"

[redis]
host="localhost"
port=6379
stream="ingest.docs"
consumer_group="rag-pdf-fixed"

[go]
port=8080
sqlite_dir="./go_sqlite_db"
