[minio]
url="localhost:9000"
access_key="minio_user"
secret_key="minio_password"
bucket="rag-pdf-source"



[sqlite]
dir="./sqlite_db"

[qdrant]
dir="./qdrant_data"

[server]
port=50051


[rag]
collection="pdf-fixed"
model="qwen3-embedding"
